language: csharp
mono: none
dotnet: 2.1.502
script:
  - dotnet restore src/NetMQ.sln
  - dotnet build -v q -f netstandard2.0 src/NetMQ/NetMQ.csproj
  - dotnet test -v n -p:ParallelizeTestCollections=false -f netcoreapp2.1 --filter Category!=Beacon src/NetMQ.Tests/NetMQ.Tests.csproj
