version: 4.0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
  - dotnet restore src/NetMQ.sln
  - dotnet build src/NetMQ.sln /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION% /verbosity:minimal
  - dotnet pack src/NetMQ/NetMQ.csproj -c Release --no-build /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
  - dotnet test --configuration Release --no-build -f netcoreapp2.1 src\NetMQ.Tests\NetMQ.Tests.csproj
  - dotnet test --configuration Release --no-build -f net462 src\NetMQ.Tests\NetMQ.Tests.csproj

artifacts:
  - path: '**\*.nupkg'
